### ISSUE TITLE
parallel-single-nowait causes post-processing error

### ISSUE THREAD

**Issue by adamtuft** [adamtuft/otter#15]
This source:

```
#include <omp.h>
#include <stdio.h>
int main(void)
{
    int num[20] = {0}, k=0;
    #pragma omp parallel
    #pragma omp single nowait
    for (k=0; k<20; k++)
    {
        num[k] = omp_get_thread_num();
    }

    return 0;
}
```

Causes this post-processing error:

```
generating chunks from event stream...
yielding chunks: 
graph chunks created:
  single_executor           1
  parallel                  1
  initial_task              1
combining chunks
nodes created            10
contracting by parallel sequence ID
nodes updated            10 ->      8 (    -2)
contracting by single-begin/end event
nodes updated             8 ->      6 (    -2)
contracting by master-begin/end event
nodes updated             6 ->      6 (     0)
deleting redundant edges due to master regions: 0
contracting by task ID & endpoint
nodes updated             6 ->      6 (     0)
contracting by task ID where there are no nested nodes
nodes updated             6 ->      6 (     0)
contracting redundant sync-enter/leave node pairs
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adam/git/otter/src/python/otter/__main__.py", line 296, in <module>
    main()
  File "/home/adam/git/otter/src/python/otter/__main__.py", line 174, in main
    g.vs['cluster'] = label_clusters(g.vs, lambda v: v['sync_cluster_id'] is not None, 'sync_cluster_id')
  File "/home/adam/git/otter/src/python/otter/helpers.py", line 97, in label_clusters
    cluster_counter = count(start=sum(not condition(v) for v in vs))
  File "/home/adam/git/otter/src/python/otter/helpers.py", line 97, in <genexpr>
    cluster_counter = count(start=sum(not condition(v) for v in vs))
  File "/home/adam/git/otter/src/python/otter/__main__.py", line 174, in <lambda>
    g.vs['cluster'] = label_clusters(g.vs, lambda v: v['sync_cluster_id'] is not None, 'sync_cluster_id')
KeyError: 'Attribute does not exist'
```

**Comment by adamtuft** [comment]
- Only present with OMP_NUM_THREADS=1
- Offending code deals with collapsing synchronisation region enter/leave nodes
- Appears to be caused by the `nowait` clause on the `single`
- Noticed that with 1 thread and the `nowait` clause there are no implicit barriers encountered, so the attribute `sync_cluster_id` is never defined.
