### ISSUE TITLE
Running BOTS fib -n 6, python fails to process trace

### ISSUE THREAD

**Issue by adamtuft** [adamtuft/otter#8]
To reproduce:

- build BOTS with clang-13
- run `OMP_TOOL_LIBRARIES=/home/adam/git/otter/lib/libotter.so bin/fib.clang.omp-tasks -n 6`
- run post-processing on the resulting trace

Error message:

```
Processing taskwait nodes:
 node 54 task(s)=[6]
 child_tasks={5}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/adam/git/otter/src/python/otter/__main__.py", line 473, in <module>
    for tcnode in g.vs.select(lambda v: v['event_type']=='task_create' and
  File "/home/adam/.local/lib/python3.8/site-packages/igraph/__init__.py", line 4544, in select
    vs = _igraph.VertexSeq.select(self, *args)
  File "/home/adam/git/otter/src/python/otter/__main__.py", line 475, in <lambda>
    v['event'].time < twnode['taskwait_enter_time'][v['parent_task_id']] and
KeyError: 4
```

**Comment by adamtuft** [comment]
Fixed in e4bace7
